### Login: obtener JWT 
POST http://localhost:8080/login 
Content-Type: application/json

{ 
  "username": "admin", 
  "password": "admin" 
}


###
GET http://localhost:8080/categories
Cookie: JSESSIONID=A6FF4D35C8652697A0AA4E617B1A046A
###
###
GET http://localhost:8080/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc3NTQ5NDYyMSwiZXhwIjoxNzc1NDk4MjIxfQ.qJ0cNhZ3Sj8i3ntuGypKJTGLNnm4kJNdnt1t8_-DIkk
###
GET http://localhost:8080/categories/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc3NTQ5NDYyMSwiZXhwIjoxNzc1NDk4MjIxfQ.qJ0cNhZ3Sj8i3ntuGypKJTGLNnm4kJNdnt1t8_-DIkk

###
POST http://localhost:8080/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc3NTQ5NDYyMSwiZXhwIjoxNzc1NDk4MjIxfQ.qJ0cNhZ3Sj8i3ntuGypKJTGLNnm4kJNdnt1t8_-DIkk
Content-Type: application/json

{
"description": "Postres"
}
###
PUT http://localhost:8080/categories/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc3NTQ5NDYyMSwiZXhwIjoxNzc1NDk4MjIxfQ.qJ0cNhZ3Sj8i3ntuGypKJTGLNnm4kJNdnt1t8_-DIkk
Content-Type: application/json

{
"description": "Bebidas"
}


###
DELETE http://localhost:8080/categories/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc3NTQ5NDYyMSwiZXhwIjoxNzc1NDk4MjIxfQ.qJ0cNhZ3Sj8i3ntuGypKJTGLNnm4kJNdnt1t8_-DIkk

##########################################################
GET http://localhost:8080/products
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc3NTQ5NDYyMSwiZXhwIjoxNzc1NDk4MjIxfQ.qJ0cNhZ3Sj8i3ntuGypKJTGLNnm4kJNdnt1t8_-DIkk

###
GET http://localhost:8080/products/4
###
POST http://localhost:8080/products
Content-Type: application/json

{
    "description": "Papas fritas",
    "price": 2000,
    "category": { "id": 2 
    }
}

###
PUT http://localhost:8080/products/4
Content-Type: application/json

{
"description": "Coca-cola",
"price": 3000,
}
###
DELETE http://localhost:8080/products/1